# Generated by Django 4.1.7 on 2023-03-20 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Question',
            new_name='Produit',
        ),
    ]
